# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: action on pull request

on:
  pull_request:
    branches: [ "main", "development"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black[jupyter]
        pip install pytest
        pip install coverage        
        pip install .
        
    - name: Run Black
      run: |
        # stop the build if not in the correct black format
        black . --check
    - name: Test with pytest
      run: |
        coverage run --branch --source=bom_analysis -m pytest -v tests || true
        coverage xml -o coverage.xml
        mkdir test-results
        cp coverage.xml test-results/test-coverage.xml
        pytest -v -o junit_family=xunit1 --junitxml=test-results/test-results.xml tests
    - name: Upload pytest test results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: ./test-results/test-results.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
    - name: Upload coverage
      uses: actions/upload-artifact@v3
      with:
        name: test-coverage
        path: ./test-results/test-coverage.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}      
